services:
  api:
    build: ./api
    container_name: iot-express-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db
    networks:
      - iot-network

  webhook:
    build:
      context: .
      dockerfile: webhook.Dockerfile
    container_name: iot-webhook-listener
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
    networks:
      - iot-network

  db:
    image: postgres:17.2
    container_name: iot-postgres-db
    environment:
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: ${API_DB_DATABASE}
    volumes:
      - iot-pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  adminer:
    image: adminer
    container_name: iot-adminer
    ports:
      - "3001:8080"
    depends_on:
      - db
    networks:
      - iot-network

volumes:
  iot-pgdata:


networks:
  iot-network:
    driver: bridge
