services:
  api:
    build: ./api
    container_name: iot-express-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
    networks:
      - iot-network

  webhook:
    build:
      context: .
      dockerfile: webhook.Dockerfile
    container_name: iot-webhook-listener
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - ${SSH_AUTH_SOCK}:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    networks:
      - iot-network

  db:
    image: postgres:17.2
    container_name: iot-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - iot-pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  adminer:
    image: adminer
    container_name: iot-adminer
    ports:
      - "3001:8080"
    depends_on:
      - db
    networks:
      - iot-network

volumes:
  iot-pgdata:


networks:
  iot-network:
    driver: bridge
